version = 1

[typescript_go]
path = "ref/typescript-go"
repository = "https://github.com/microsoft/typescript-go.git"
commit = "9c19dee6ab88ae11444837f16efa16a6b3dc9f59"
tree = "e1257b20f345c9191c8b12c8e1770618c841129f"
committer_date = "2026-04-07T21:02:45Z"
author = "Mateusz Burzyński"
subject = "Properly recognize all symbol flags on imported reexported symbols in completions code (#3359)"
