version = 1

[typescript_go]
path = "ref/typescript-go"
repository = "https://github.com/microsoft/typescript-go.git"
commit = "ba858e5c6852160ff69184d7fd7db77b348e246c"
tree = "49248a2c230e711b1c49ea17b84fee7767d97c4c"
committer_date = "2026-04-23T21:55:46Z"
author = "Andrew Branch"
subject = "Include compilerOptions.types in auto-import packages (#3536)"
