export const AST_NODE_TYPES = Object.freeze({
  ArrayExpression: "ArrayExpression",
  ArrowFunctionExpression: "ArrowFunctionExpression",
  AssignmentExpression: "AssignmentExpression",
  AwaitExpression: "AwaitExpression",
  BinaryExpression: "BinaryExpression",
  BlockStatement: "BlockStatement",
  CallExpression: "CallExpression",
  CatchClause: "CatchClause",
  ChainExpression: "ChainExpression",
  ConditionalExpression: "ConditionalExpression",
  ExpressionStatement: "ExpressionStatement",
  ForInStatement: "ForInStatement",
  ForOfStatement: "ForOfStatement",
  FunctionDeclaration: "FunctionDeclaration",
  FunctionExpression: "FunctionExpression",
  Identifier: "Identifier",
  IfStatement: "IfStatement",
  ImportDeclaration: "ImportDeclaration",
  Literal: "Literal",
  LogicalExpression: "LogicalExpression",
  MemberExpression: "MemberExpression",
  MethodDefinition: "MethodDefinition",
  NewExpression: "NewExpression",
  ObjectExpression: "ObjectExpression",
  Program: "Program",
  Property: "Property",
  ReturnStatement: "ReturnStatement",
  SequenceExpression: "SequenceExpression",
  SpreadElement: "SpreadElement",
  SwitchStatement: "SwitchStatement",
  TaggedTemplateExpression: "TaggedTemplateExpression",
  TemplateLiteral: "TemplateLiteral",
  ThrowStatement: "ThrowStatement",
  TryStatement: "TryStatement",
  UnaryExpression: "UnaryExpression",
  UpdateExpression: "UpdateExpression",
  VariableDeclaration: "VariableDeclaration",
  VariableDeclarator: "VariableDeclarator",
  TSAnyKeyword: "TSAnyKeyword",
  TSAsExpression: "TSAsExpression",
  TSBooleanKeyword: "TSBooleanKeyword",
  TSCallSignatureDeclaration: "TSCallSignatureDeclaration",
  TSConditionalType: "TSConditionalType",
  TSConstructSignatureDeclaration: "TSConstructSignatureDeclaration",
  TSDeclareFunction: "TSDeclareFunction",
  TSEnumDeclaration: "TSEnumDeclaration",
  TSExpressionWithTypeArguments: "TSExpressionWithTypeArguments",
  TSFunctionType: "TSFunctionType",
  TSImportType: "TSImportType",
  TSIndexedAccessType: "TSIndexedAccessType",
  TSInferType: "TSInferType",
  TSInterfaceDeclaration: "TSInterfaceDeclaration",
  TSLiteralType: "TSLiteralType",
  TSMappedType: "TSMappedType",
  TSMethodSignature: "TSMethodSignature",
  TSModuleDeclaration: "TSModuleDeclaration",
  TSNeverKeyword: "TSNeverKeyword",
  TSNullKeyword: "TSNullKeyword",
  TSNumberKeyword: "TSNumberKeyword",
  TSObjectKeyword: "TSObjectKeyword",
  TSPropertySignature: "TSPropertySignature",
  TSStringKeyword: "TSStringKeyword",
  TSThisType: "TSThisType",
  TSTupleType: "TSTupleType",
  TSTypeAliasDeclaration: "TSTypeAliasDeclaration",
  TSTypeAnnotation: "TSTypeAnnotation",
  TSTypeAssertion: "TSTypeAssertion",
  TSTypeLiteral: "TSTypeLiteral",
  TSTypeOperator: "TSTypeOperator",
  TSTypeParameter: "TSTypeParameter",
  TSTypeParameterDeclaration: "TSTypeParameterDeclaration",
  TSTypeParameterInstantiation: "TSTypeParameterInstantiation",
  TSTypePredicate: "TSTypePredicate",
  TSTypeReference: "TSTypeReference",
  TSUndefinedKeyword: "TSUndefinedKeyword",
  TSUnionType: "TSUnionType",
  TSUnknownKeyword: "TSUnknownKeyword",
  TSVoidKeyword: "TSVoidKeyword",
} as const);

export const AST_TOKEN_TYPES = Object.freeze({
  Boolean: "Boolean",
  Identifier: "Identifier",
  JSXIdentifier: "JSXIdentifier",
  JSXText: "JSXText",
  Keyword: "Keyword",
  Null: "Null",
  Numeric: "Numeric",
  PrivateIdentifier: "PrivateIdentifier",
  Punctuator: "Punctuator",
  RegularExpression: "RegularExpression",
  String: "String",
  Template: "Template",
} as const);

export const TSESTree = Object.freeze({
  AST_NODE_TYPES,
  AST_TOKEN_TYPES,
});
