/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function isUnsafeAssignment(inputJson: string): boolean
export declare function isUnsafeReturn(inputJson: string): boolean
/**
 * Returns the package version exposed by the native addon.
 *
 * # Examples
 *
 * ```
 * assert_eq!(tsgo_rs_node::version(), env!("CARGO_PKG_VERSION"));
 * ```
 */
export declare function version(): string
/** Thin synchronous wrapper around the Rust stdio API client. */
export declare class TsgoApiClient {
  /** Spawns a new client from a JSON-encoded spawn config. */
  static spawn(optionsJson: string): TsgoApiClient
  /** Calls `initialize` and returns the raw JSON response. */
  initializeJson(): string
  /** Parses a `tsconfig` through tsgo and returns the JSON response. */
  parseConfigFileJson(file: string): string
  /** Applies file changes and returns a serialized snapshot record. */
  updateSnapshotJson(paramsJson?: string | undefined | null): string
  /** Fetches a source file through the binary endpoint. */
  getSourceFile(snapshot: string, project: string, file: string): Buffer | null
  /** Resolves the intrinsic string type for a project. */
  getStringTypeJson(snapshot: string, project: string): string
  /** Renders a type back to a string representation. */
  typeToString(snapshot: string, project: string, typeHandle: string, location?: string | undefined | null, flags?: number | undefined | null): string
  /** Sends an arbitrary JSON endpoint request. */
  callJson(method: string, paramsJson?: string | undefined | null): string
  /** Sends an arbitrary binary endpoint request. */
  callBinary(method: string, paramsJson?: string | undefined | null): Buffer | null
  /** Releases a tsgo handle explicitly. */
  releaseHandle(handle: string): void
  /** Closes the underlying worker process. */
  close(): void
}
/** Mutable virtual document mirrored through the LSP overlay layer. */
export declare class TsgoVirtualDocument {
  /** Creates an `untitled:` document. */
  static untitled(path: string, languageId: string, text: string): TsgoVirtualDocument
  /** Creates an in-memory `tsgo://` document. */
  static inMemory(authority: string, path: string, languageId: string, text: string): TsgoVirtualDocument
  /** Returns the document URI. */
  get uri(): string
  /** Returns the language identifier. */
  get languageId(): string
  /** Returns the current version number. */
  get version(): number
  /** Returns the current full text. */
  get text(): string
  /** Serializes the full document state. */
  stateJson(): string
  /** Replaces the entire document text. */
  replace(text: string): void
  /** Applies a batch of JSON-encoded LSP changes. */
  applyChangesJson(changesJson: string): string
}
/** N-API wrapper for the distributed orchestration layer. */
export declare class TsgoDistributedOrchestrator {
  /** Creates a new in-process Raft cluster. */
  constructor(nodeIds: Array<string>)
  /** Starts a leader election and returns the resulting term. */
  campaign(nodeId: string): number
  /** Returns the current leader identifier. */
  leaderId(): string | null
  /** Serializes the leader state. */
  stateJson(): string | null
  /** Serializes the state for a single node. */
  nodeStateJson(nodeId: string): string | null
  /** Serializes a replicated document if it exists. */
  documentJson(nodeId: string, uri: string): string | null
  /** Replicates an opened document and returns the serialized state. */
  openVirtualDocumentJson(leaderId: string, documentJson: string): string
  /** Applies replicated incremental changes and returns the serialized state. */
  changeVirtualDocumentJson(leaderId: string, uri: string, changesJson: string): string
  /** Removes a replicated document. */
  closeVirtualDocument(leaderId: string, uri: string): void
}
